services:
  cv-site:
    container_name: cv-site
    image: ghcr.io/peterkelemen2/cv-site:latest
    restart: unless-stopped

    networks:
      - proxy

    labels:
      - 'traefik.enable=true'

      - 'traefik.http.routers.cv.rule=Host(`petidev.hu`)'
      - 'traefik.http.routers.cv.entrypoints=websecure'
      - 'traefik.http.routers.cv.tls.certresolver=le'

      - 'traefik.http.services.cv.loadbalancer.server.port=80'

networks:
  proxy:
    external: true
